app/app/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from .settings import STATIC_ROOT, STATIC_URL, DEBUG
from .views import about, imprint, license, privacy, faq

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("users/", include("django.contrib.auth.urls")),
    path("", include("projects.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("imprint/", imprint, name="imprint"),
    path("privacy/", privacy, name="privacy"),
    path("about/", about, name="about"),
    path("license/", license, name="license"),
    path("faq", faq, name="faq"),
    # path('plotly_dash/', include('dashplots.urls')),
    path("django_plotly_dash/", include("django_plotly_dash.urls")),
) + [re_path(r"^i18n/", include("django.conf.urls.i18n"))]

if DEBUG:
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

app/dashboard/forms.py
from dashboard.helpers import (
    GRAPH_TIMESERIES,
    GRAPH_TIMESERIES_STACKED,
    GRAPH_CAPACITIES,
    GRAPH_SANKEY,
    GRAPH_SENSITIVITY_ANALYSIS,
)
from dashboard.models import (
    ReportItem,
    AssetsResults,
    SensitivityAnalysisGraph,
    get_project_sensitivity_analysis,
)
from django import forms
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from projects.models import ENERGY_VECTOR, Project


class ReportItemForm(ModelForm):

    scenarios = forms.ChoiceField(label=_("Scenario"))

    def __init__(self, *args, **kwargs):
        proj_id = kwargs.pop("proj_id", None)
        multi_scenario = kwargs.pop("multi_scenario", False)
        super().__init__(*args, **kwargs)

        if multi_scenario is True:
            self.fields["scenarios"] = forms.MultipleChoiceField(label=_("Scenarios"))

        if proj_id is not None:
            project = Project.objects.get(id=proj_id)
            self.fields["scenarios"].choices = [
                c
                for c in project.get_scenarios_with_results().values_list("id", "name")
            ]

    class Meta:
        model = ReportItem
        fields = ["report_type", "title"]
        labels = [_("Type of report item"), _("Title")]

    field_order = ["scenarios", "report_type", "title"]


class TimeseriesGraphForm(forms.Form):
    energy_vector = forms.MultipleChoiceField(
        label=_("Energy vector"), choices=ENERGY_VECTOR, initial=ENERGY_VECTOR[1][0]
    )
    y = forms.MultipleChoiceField(label=_("Timeseries variable(s)"), choices=tuple())

    def __init__(self, *args, **kwargs):
        scen_ids = kwargs.pop("scenario_ids", None)
        super().__init__(*args, **kwargs)

        if scen_ids is not None:
            # list available assets parameters for each simulations
            assets_results_across_simulations = AssetsResults.objects.filter(
                simulation__scenario__id__in=scen_ids
            )
            choices = None
            for assets_results in assets_results_across_simulations:
                new_choices = [(n, n) for n in assets_results.available_timeseries]
                if choices is None:
                    choices = set(new_choices)
                else:
                    choices = choices.intersection(new_choices)

            self.fields["y"].choices = tuple(choices)


class StackedTimeseriesGraphForm(forms.Form):
    energy_vector = forms.ChoiceField(
        label=_("Energy vector"), choices=ENERGY_VECTOR, initial=ENERGY_VECTOR[1][0]
    )
    y = forms.MultipleChoiceField(label=_("Timeseries variable(s)"), choices=tuple())

    def __init__(self, *args, **kwargs):
        scen_ids = kwargs.pop("scenario_ids", None)
        super().__init__(*args, **kwargs)

        if scen_ids is not None:
            # list available assets parameters for each simulations
            assets_results_across_simulations = AssetsResults.objects.filter(
                simulation__scenario__id__in=scen_ids
            )
            choices = None
            for assets_results in assets_results_across_simulations:
                new_choices = [(n, n) for n in assets_results.available_timeseries]
                if choices is None:
                    choices = set(new_choices)
                else:
                    choices = choices.intersection(new_choices)

            self.fields["y"].choices = tuple(choices)


class StackedCapacitiesGraphForm(forms.Form):
    energy_vector = forms.ChoiceField(
        label=_("Energy vector"), choices=ENERGY_VECTOR, initial=ENERGY_VECTOR[1][0]
    )
    y = forms.MultipleChoiceField(label=_("Component(s)"), choices=tuple())

    def __init__(self, *args, **kwargs):
        scen_ids = kwargs.pop("scenario_ids", None)
        super().__init__(*args, **kwargs)

        if scen_ids is not None:
            # list available assets parameters for each simulations
            assets_results_across_simulations = AssetsResults.objects.filter(
                simulation__scenario__id__in=scen_ids
            )
            choices = None
            for assets_results in assets_results_across_simulations:
                new_choices = [
                    (n, n)
                    for n in assets_results.available_timeseries
                    if assets_results.single_asset_type_oemof(n) != "sink"
                ]
                if choices is None:
                    choices = set(new_choices)
                else:
                    choices = choices.intersection(new_choices)
            self.fields["y"].choices = tuple(choices)


class SankeyGraphForm(forms.Form):
    energy_vector = forms.MultipleChoiceField(
        label=_("Energy vector"), choices=ENERGY_VECTOR, initial=ENERGY_VECTOR[1][0]
    )

    def __init__(self, *args, **kwargs):
        scen_ids = kwargs.pop("scenario_ids", None)
        super().__init__(*args, **kwargs)


class SensitivityAnalysisGraphForm(ModelForm):
    def __init__(self, *args, **kwargs):
        proj_id = kwargs.pop("proj_id", None)
        super().__init__(*args, **kwargs)

        if proj_id is not None:
            project = Project.objects.get(id=proj_id)
            self.fields["analysis"].choices = [
                (sa.id, sa.name) for sa in get_project_sensitivity_analysis(project)
            ]

    class Meta:
        model = SensitivityAnalysisGraph
        fields = ["analysis", "title", "y"]
        labels = [
            _("Sensitivity analysis"),
            _("Graph title"),
            _("Parameter of interest"),
        ]

    field_order = ["analysis", "title", "y"]


def graph_parameters_form_factory(report_type, *args, **kwargs):
    """Linked to dashboard/models.py:ReportItem.fetch_parameters_values"""
    if report_type == GRAPH_TIMESERIES:
        answer = TimeseriesGraphForm(*args, **kwargs)
    if report_type == GRAPH_TIMESERIES_STACKED:
        answer = StackedTimeseriesGraphForm(*args, **kwargs)
    if report_type == GRAPH_CAPACITIES:
        answer = StackedCapacitiesGraphForm(*args, **kwargs)
    # GRAPH_BAR,
    # GRAPH_PIE,
    # GRAPH_LOAD_DURATION,
    # GRAPH_SANKEY,
    if report_type == GRAPH_SANKEY:
        answer = SankeyGraphForm(*args, **kwargs)
    if report_type == GRAPH_SENSITIVITY_ANALYSIS:
        answer = SensitivityAnalysisGraphForm(*args, **kwargs)
    return answer

app/templates/report/compare_scenario.html
{% extends 'scenario/scenario_results_page.html' %}
{% load static %}
{% load custom_filters %}
{% load custom_template_tags %}
{% load i18n %}


{% block title %}{% translate "Compare Scenarios" %}{% endblock title %}


{% block dashboard %}
<div class="dashboard-options sticky-top">
	<div>
		<div class="row">
			<div class="dashboard__scenarios">
				<div class="dashboard__select-scenarios">
					<label for="results-scenarios" class="form-label">{% translate "Scenarios" %}</label>
					<select name="results-scenarios" id="results-scenarios" placeholder="This is a placeholder" multiple onchange="update_selected_multi_scenarios(this)">
						{% for scenario in scenario_list %}
						<option value="{{ scenario.id }}" {% if scenario.id in selected_scenarios %} selected {% endif %}>{{ scenario.name }}</option>
						{% empty %}
						{% translate "You have no scenario with completed simulation, please run simulations to display results" %}
						{% endfor %}
					</select>
				</div>
				{% if scenario_list %}
				<div class="dashboard__add">
					<button class="btn btn--small btn--transparent" type="submit" onclick="javascript:showCreateReportItemModal(event)">
						<span class="icon icon-add"></span>
						{% translate "Add chart" %}
					</button>
				</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>
<section class="dashboard">
	<div>
		<div class="row">
			<div class="col" id="report_items">
				{% include "report/graph_template.html" with id="all_timeseries" title="All timeseries" %}
				{% include "report/graph_template.html" with id="capacities" title="Installed and optimized capacities" %}
			</div>
		</div>
	</div>
</section>

{% endblock dashboard %}


{% block results_end_body_scripts %}
<script>
$(document).ready(function () {
    // add search field to the kpi info modal
    $('#kpiTable').DataTable();
    // update the kpi table
    //update_kpi_table_style(document.getElementById("kpi-table-style"));
    if(fetchSelectedScenarios().length > 0 ){
    	scenario_visualize_timeseries();
    	scenario_visualize_capacities();
    }
});

function update_selected_multi_scenarios(target){

		const scen_ids = fetchSelectedScenarios();
		console.log(scen_ids);
    if( scen_ids != null){
        $.ajax({
        		headers: {'X-CSRFToken': '{{ csrf_token }}'},
            url: "{% url 'update_selected_multi_scenarios' proj_id %}",
            type: "POST",
            data: {"scen_ids": JSON.stringify(scen_ids)},
            dataType: "json",
            success: async (data) => {
                //call functions which update graphs below

                /* Update the kpi table */
                //update_kpi_table_style(document.getElementById("kpi-table-style"));
                if(scen_ids.length > 0){
                	scenario_visualize_timeseries();
                	scenario_visualize_capacities();
                }
            },
        });
    }
}

document.getElementById('compare-scenario-link').classList.add('active');

var dropdownElement = new Choices('#results-scenarios', {
	removeItemButton: true,
	allowHTML: false
});

</script>
{% endblock results_end_body_scripts %}

app/templates/report/graph_template.html
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}

{% comment %}
Here is a list of the parameters one can provide to this template

id:
    the id of the modal (should be unique to the modal within same html template
title:
    the text display in the title bar of the modal
{% endcomment %}


<div class="chart" style="height: fit-content;">
    <div class="chart__header">
        <div>
            <span class="title">{% translate title %}</span>
        </div>
        <div class="dropdown">
            <button class="btn dropdown-toggle btn--transparent" type="button" id="dropdownMenuTS" data-bs-toggle="dropdown" aria-expanded="false">
                <span class="icon icon-more"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuTS">
                <li><a class="dropdown-item" href="{% url 'not_implemented' %}?url={{ request.get_full_path }}">{% translate 'Export as .xls' %}</a></li>
                <li><a class="dropdown-item" href="{% url 'not_implemented' %}?url={{ request.get_full_path }}">{% translate 'Export as PDF' %}</a></li>
            </ul>
        </div>
    </div>
    <div class="chart__plot">
        <div id="{{ id }}"></div>
    </div>
</div>

app/templates/report/report_item_parameters_form.html
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{{ report_item_form|crispy }}
{{ graph_parameters_form|crispy }}

app/templates/report/sa_parameters_form.html
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% for param in output_parameters %}
<option value="{{ param.name }}">{% translate param.verbose %}</option>
{% endfor %}

app/templates/report/sensitivity_analysis.html
{% extends 'scenario/scenario_results_page.html' %}
{% load static %}
{% load custom_filters %}
{% load custom_template_tags %}
{% load i18n %}


{% block title %}{% translate "Sensitivity analysis" %}{% endblock title %}


{% block dashboard %}

    <section class="dashboard">
        <div>
            <div class="row">
                <div class="dashboard__scenarios">
                    <h2>My sensitivity analysis</h2>
                    <div class="scenario-select">
                        {% for sa in sa_list %}
                        {% if sa.id|stringformat:'s' in request|get_selected_scenarios:proj_id %}
                            {% setvar "selected" as selected %}
                        {% else%}
                            {% setvar "" as selected %}
                        {% endif %}
                            <button id="sa-{{ proj_id }}-{{ sa.id}}" class="scenario-select__item {{ selected }}" onclick="update_selected_sa(this)">
                                {{ sa.name }}
                            </button>
                        {% empty %}
                            {% translate "You have no sensitivity analysis with completed simulation, please run simulations to display results" %}
                        {% endfor %}


                    </div>
                </div>
            </div>
            {% if sa_list %}
            <div class="row dashboard__create">
                <div class="col">
                  <button class="btn btn--medium" onclick="javascript:showCreateSaGraphModal(event)">
                    <span class="icon icon-add"></span>
                    {% translate "Create graph" %}
                  </button>
                </div>
            </div>
            <div class="row">
                <div class="col" id="report_items">
                </div>
            </div>
            {% endif %}
        </div>
    </section>

{% endblock dashboard %}


{% block results_end_body_scripts %}
<script>

document.getElementById('sensitivity-analysis-link').classList.add('active');



    /** Add a new sensitivity graph **/

    function showCreateSaGraphModal(event){
        showModal(
            event,
            modalId="createReportItemModal",
            attrs={
                action: `{% url 'sensitivity_analysis_create_graph' proj_id %}`,
            }
        )

        //const urlSaForm = document.getElementById("createSaGraphModal").querySelector("form").getAttribute("graph-parameter-url");

        $("#id_analysis").change(function () {
          var saId= $(this).val();

          $.ajax({
            headers: {'X-CSRFToken': `{{ csrf_token }}` },
            type: "POST",
            url: `{% url 'ajax_get_sensitivity_analysis_parameters' %}`,
            data: {
              'sa_id': saId
            },
            success: function (data) {
              console.log(data)
              $("#id_y").html(data);
            }
          });
        });

    }





</script>
{% endblock results_end_body_scripts %}

app/templates/report/single_scenario.html
{% extends 'scenario/scenario_results_page.html' %}
{% load static %}
{% load custom_filters %}
{% load custom_template_tags %}
{% load i18n %}

{% block title %}{% translate "Single Scenarios" %}{% endblock title %}


{% block export-results %}
{% endblock export-results %}


{% block dashboard %}

{% load plotly_dash %}
<div class="{% plotly_class name='SimpleExample' %}">
	{% plotly_app name='SimpleExample' %}
</div>
{% endblock dashboard %}


{% block results_end_body_scripts %}

{% endblock results_end_body_scripts %}